name: Test SSH
on: [push]

jobs:
  ssh-test:
    runs-on: ubuntu-latest
    steps:
      - name: SSH test
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: hostname
